# Generated by Django 3.2.4 on 2021-07-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_arte_idcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio del arte'),
        ),
    ]
