# Generated by Django 3.2.4 on 2021-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_arte_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='url',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='', upload_to='artes_img', verbose_name='Imagen'),
        ),
    ]
