# Generated by Django 3.2.4 on 2021-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_imagen_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='historiaArte',
        ),
        migrations.AlterField(
            model_name='arte',
            name='descripcionArte',
            field=models.TextField(verbose_name='Descripcion de el arte'),
        ),
    ]
