# Generated by Django 3.2.4 on 2021-07-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210706_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='tecnicaUsada',
        ),
    ]
