# Generated by Django 3.2.4 on 2021-07-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_arte_tecnicausada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='idArte',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Arte'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='idArtista',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Artista'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Categoria'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='idImagen',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Imagen'),
        ),
    ]
