# Generated by Django 3.2.4 on 2021-07-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdmin', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de administrador')),
                ('email', models.CharField(max_length=250, verbose_name='Correo electronico')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
